---
- name: Docker set-up
  hosts: slave_deb
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Signing Key Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add repo Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker-ce

    - name: Install Docker-CE & Docker Compose 
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes
